dist: xenial

language: python
python:
  - "3.7"

notifications:
  email:
    - scox@renci.org
    - groupe@cfsnc.org

# command to install dependencies
install:
  - pip install -r tranql/requirements.txt

env:
  global:
    - PATH=$PWD/bin:$PATH

# command to run tests
script:
  - tranql test

after_success:
  - coveralls
